<?php
$LANG_ = array(

"language_attributes" => array(	"1" => "en-US" ),

"english" => array(

	"button" => array(
		"1" 			=> __("Add","premiumpress"),
		"2" 			=> __("Edit","premiumpress"),
		"3" 			=> __("Delete","premiumpress"),
		"4" 			=> __("More Details","premiumpress"),
		"5" 			=> __("Logout","premiumpress"),
		"6" 			=> __("Save Changes","premiumpress"),
		"7" 			=> __("Back","premiumpress"),
		"8" 			=> __("Cancel","premiumpress"),
		"9" 			=> __("Reply","premiumpress"),
		"10" 			=> __("Continue","premiumpress"),
		"11" 			=> __("Search","premiumpress"),
		"12" 			=> __("Visit Website","premiumpress"),
		"13" 			=> __("More Info","premiumpress"),
		"14" 			=> __("Contact Owner","premiumpress"),
		"15" 			=> __("Share","premiumpress"),
		"16" 			=> __("Login","premiumpress"),
		"19" 			=> __("Free","premiumpress"),
		"21" 			=> __("Pay Now","premiumpress"),
		"22" 			=> __("Pay Now","premiumpress"),
		"23" 			=> __("Print","premiumpress"),
		"25" 			=> __("Yes","premiumpress"),
		"26" 			=> __("No","premiumpress"),
		"27" 			=> __("Page","premiumpress"),
		"28" 			=> __("Subscribe","premiumpress"),
		"29" 			=> __("example@hotmail.com","premiumpress"),
		"30" 			=> __("Submit Listing","premiumpress"),
		"31" 			=> __("--- all departments ---","premiumpress"),
		"32" 			=> __("Add Favorites","premiumpress"),
		"33" 			=> __("Remove Favorites","premiumpress"),
		"34" 			=> __("Get Code","premiumpress"),
		"35" 			=> __("View All Listings","premiumpress"),
		"36" 			=> __("in","premiumpress"),
		"37" 			=> __("within","premiumpress"),
		"38" 			=> __("distance","premiumpress"),
		"39" 			=> __("Zip/Postal Code","premiumpress"),
		"40" 			=> __("Read More","premiumpress"),
		"41" 			=> __("Printable","premiumpress"),
		"42"			=> __("ToolBox","premiumpress"),
		"43"			=> __("Compare","premiumpress"),
		"44" 			=> __("--- all categories ---","premiumpress"),
		"45" 			=> __("--- all position types ---","premiumpress"),
		"46" 			=> __("--- all locations ---","premiumpress"),
		"47" 			=> __("Vote Up","premiumpress"),
		"48" 			=> __("Vote Down","premiumpress"),
		"49" 			=> __("Store","premiumpress"),
		"50" 			=> __("List","premiumpress"),
		"51" 			=> __("Grid","premiumpress"),
		"52" 			=> __("Map","premiumpress"),
		"53" 			=> __("Report","premiumpress"),
		"54" 			=> __("Featured","premiumpress"),
		"55"			=> __("Blog","premiumpress"),
		"56"			=> __("Open in Google Maps","premiumpress"),
		"57"			=> __("View on Map","premiumpress"),
		"58"			=> __("Caption","premiumpress"),
		"59"			=> __("Members Area","premiumpress"),
		"60"			=> __("Search Website","premiumpress"),

		"61"			=> __("Next","premiumpress"),
		"62"			=> __("Previous","premiumpress"),

		"63"			=> __("Buy Now","premiumpress"),
		"64"			=> __("Sold Out","premiumpress"),
	),

	"date" => array(
		"1" 		=> __("Day","premiumpress"),
		"2" 		=> __("Days","premiumpress"),
		"second" 	=> __("second","premiumpress"),
		"minute" 	=> __("minute","premiumpress"),
		"hour" 		=> __("hour","premiumpress"),
		"day" 		=> __("day","premiumpress"),
		"week" 		=> __("week","premiumpress"),
		"month" 	=> __("month","premiumpress"),
		"year" 		=> __("year","premiumpress"),
		"decade" 	=> __("decade","premiumpress"),
		"seconds" 	=> __("seconds","premiumpress"),
		"minutes" 	=> __("minutes","premiumpress"),
		"hours" 	=> __("hours","premiumpress"),
		"days" 		=> __("days","premiumpress"),
		"weeks" 	=> __("weeks","premiumpress"),
		"months" 	=> __("months","premiumpress"),
		"years" 	=> __("years","premiumpress"),
		"decades" 	=> __("decades","premiumpress"),
		"bad" 		=> __("Bad date","premiumpress"),
	),

	"validate" => array(
		"0"			=> __("Please complete all fields.","premiumpress"),
		"1" 		=> __("Please enter your first name.","premiumpress"),
		"2" 		=> __("Please enter your last name.","premiumpress"),
		"3" 		=> __("Please enter a valid email address.","premiumpress"),
		"4" 		=> __("Your passwords do not match. Please check and try again.","premiumpress"),
		"5" 		=> __("Are you sure you want to do this?","premiumpress"),
		"6" 		=> __("What is the sum of %a + %b ?","premiumpress"),
		"7" 		=> __("Please enter a title for your item.","premiumpress"),
		"8" 		=> __("Please enter a search description for your item.","premiumpress"),
		"9" 		=> __("Please enter a few tags/keywords for your item.","premiumpress"),
		"10" 		=> __("Only JPG, PNG, GIF, PDF or FLV (video) files are allowed.","premiumpress"),
		"11" 		=> __("Uploading..","premiumpress"),
		"12" 		=> __("File type not supported.","premiumpress"),
		"13" 		=> __("Invalid file","premiumpress"),
		"14"		=> __("The upload directory is not writ able. Please contact the admin.","premiumpress"),
		"15"		=> __("has been added to your list.","premiumpress"),
		"16"		=> __("Click Here to view your list.","premiumpress"),
		"17"		=> __("is already on your list.","premiumpress"),
		"18"		=> __("item removed","premiumpress"),
		"20"		=> __("Please enter a username.","premiumpress"),
		"21"		=> __("Please enter a password.","premiumpress"),
		"22"		=> __("Please select a package to continue.","premiumpress"),
		"23"		=> __("You have entered and invalid email address","premiumpress"),
		"24"		=> __("A confirmation email has been sent","premiumpress"),
		"25"		=> __("<b>Members Only</b> Please login to use this feature.","premiumpress"),
		"26"		=> __("0 results found","premiumpress"),
		"27"		=> __("Please upload a display image.","premiumpress"),
		"28"		=> __("Please add more content to your listing description.","premiumpress"),
		"29"		=> __("Please select a category.","premiumpress"),
		"lo_a_favorite"		=> __("Removed From Favorites","premiumpress"),
		"lo_r_favorite"		=> __("Added To Favorites","premiumpress"),
		"lo_a_wishlist"		=> __("<b>Listing Removed</b> This item has been removed from your list.","premiumpress"),
		"lo_r_wishlist"		=> __("<b>Listing Added</b> This item has been added to your list.","premiumpress"),
		"lo_a_blocked"		=> __("<b>User Block Removed</b> This user has been removed from your list.","premiumpress"),
		"lo_r_blocked"		=> __("<b>User Block Added</b> This user has been added to your list.","premiumpress"),
		"lo_a_friends"		=> __("<b>Friend Removed</b> This user has been removed from your list.","premiumpress"),
		"lo_r_friends"		=> __("<b>Friend Added</b> This user has been added to your list.","premiumpress"),

		"30"		=> __("Please login to access this page","premiumpress"),
		"31"		=> __("Not enough information from your social profile could be found. Please use the register page to create a new profile on our website.","premiumpress"),

	),

	"author" => array(
		"1"			=> __("This user has published %a listings.","premiumpress"),
		"2"			=> __("View All Listings","premiumpress"),
		"fulltime" => __("Full-time","premiumpress"),
		"parttime" => __("Part-time","premiumpress"),
		"contract" => __("Contract","premiumpress"),
		"internship" => __("Internship","premiumpress"),
		"temporary" => __("Temporary","premiumpress"),
		"3" => __("Position Type","premiumpress"),
		"4" => __("Payment Type","premiumpress"),
		"5" => __("Amount","premiumpress"),
		"6" => __("Add New Job","premiumpress"),
		"7" => __("View All job Listings","premiumpress"),
		"8" => __("Project ID","premiumpress"),
		"9" => __("Posted","premiumpress"),
		"10" => __("Please confirm you want to accept this users proposal. All other proposals will be declined and new bidding disabled.","premiumpress"),
		"11" => __("Hourly Rate","premiumpress"),
		"12" => __("Budget Amount","premiumpress"),
		"13" => __("Fixed Salary (monthly)","premiumpress"),
		"14" => __("Fixed Salary (annually)","premiumpress"),
		"15" => __("Author","premiumpress"),
		"16" => __("Negotiable","premiumpress"),
		"17" => __("If the amount is negotiable enter the value 0","premiumpress"),
		"18" => __("Display Type","premiumpress"),
		"19" => __("Members bid online","premiumpress"),
		"20" => __("Members apply via email","premiumpress"),
		"21" => __("Explain why you should be selected for this job below;","premiumpress"),
		"22" => __("Enter the amount of monies your willing to accept to complete this work.","premiumpress"),
		"23" => __("Submit Proposal","premiumpress"),
		"24" => __("Please enter a few comments about your proposal.","premiumpress"),
		"25" => __("Accept Proposal","premiumpress"),
		"26" => __("says","premiumpress"),
		"26a" => __("said on","premiumpress"),
		"27" => __("File Removed Successfully.","premiumpress"),
		"28" => __("Upload Curriculum Vitae (CV) or Resume.","premiumpress"),
		"29" => __("You do not have permission to access this file.","premiumpress"),
		"30" => __("Apply for Job","premiumpress"),
		"31" => __("Submit Application","premiumpress"),
		"32" => __("Upload your CV (Curriculum Vitae) via the members area and it can be attached to this application.","premiumpress"),
		"33" => __("Login to Apply Online","premiumpress"),
	),

	"widgets" => array(
		"1"			=> __("%a days access","premiumpress"),
		"2"			=> __("search radius","premiumpress"),
		"3"			=> __("auto","premiumpress"),
		"4"			=> __("mile","premiumpress"),
		"5"			=> __("miles","premiumpress"),
		"6"			=> __("mile radius","premiumpress"),
		"7"			=> __("Other posts by this author","premiumpress"),
		"8"			=> __("Change Location","premiumpress"),
		"9"			=> __("Where are you now?","premiumpress"),
		"10"		=> __("Set your location by clicking on the map below or typing in your address below.","premiumpress"),
		"11"		=> __("Update My Location","premiumpress"),
		"12"		=> __("distance:","premiumpress"),
		"13"		=> __("Kilometers","premiumpress"),
		"14"		=> __("Nautical Miles","premiumpress"),
		"15"		=> __("Miles","premiumpress"),
		"16"		=> __("My Location","premiumpress"),
		"17"		=> __("hide all markers","premiumpress"),
		"18"		=> __("show/hide","premiumpress"),
		"19"		=> __("GO","premiumpress"),
		"20"		=> __("Email Author","premiumpress"),
		"21"		=> __("Send Message","premiumpress"),
		"22"		=> __("Add To Friends","premiumpress"),
		"23"		=> __("Add To Blocked List","premiumpress"),
		"24"		=> __("View Profile","premiumpress"),
		"25"		=> __("%a ago.","premiumpress"),
 		"26"		=> __("Last online","premiumpress"),
 		"27"		=> __("to","premiumpress"),
		"28"		=> __("Filter by Rating ","premiumpress"),
		"29"		=> __("Stars","premiumpress"),
		"30"		=> __("Have a question?","premiumpress"),
		"31"		=> __("review","premiumpress"),
		"32"		=> __("reviews","premiumpress"),
		"33"		=> __("vote","premiumpress"),
		"34"		=> __("votes","premiumpress"),
		"35"		=> __("Join Now","premiumpress"),

		"36" 			=> __("Thank You!","premiumpress"),
		"37" 			=> __("You've Already Rated!","premiumpress"),
		"38" 			=> __("Success Meter","premiumpress"),

		"39" 			=> __("Works","premiumpress"),
		"40" 			=> __("Doesn't","premiumpress"),
		"41" 			=> __("votes","premiumpress"),
	),


	"order_status" => array(
		"1" 			=> __("Paid","premiumpress"),
		"2" 			=> __("Refunded","premiumpress"),
		"3" 			=> __("Incomplete","premiumpress"),
		"4" 			=> __("Failed","premiumpress"),
		"5" 			=> __("Paid &amp; Complete","premiumpress"),
		"title0" 		=> __("My Orders","premiumpress"),
		"title1" 		=> __("Order ID","premiumpress"),
		"title2" 		=> __("Date","premiumpress"),
		"title3" 		=> __("Status","premiumpress"),
		"title4" 		=> __("Amount","premiumpress"),
	),

	"head" => array(
		"1" 		=> __("Home","premiumpress"),
		"2" 		=> __("Advanced Search","premiumpress"),
		"4" 		=> __("Dashboard","premiumpress"),
		"5" 		=> __("Login","premiumpress"),
		"6"			=> __("Register","premiumpress"),
		"7"			=> __("Quick Search","premiumpress"),
		"8"			=> __("Notifications","premiumpress"),

	),

	"homepage" => array(
		"1" 			=> __("Website Search","premiumpress"),
		"2" 			=> __("New Arrivals","premiumpress"),
 		"3" 			=> __("Popular Categories","premiumpress"),
		"4" 			=> __("Add Listing","premiumpress"),
		"5" 			=> __("Manage Listings","premiumpress"),
		"6" 			=> __("What are you looking for?","premiumpress"),
		"7" 			=> __("Keyword or phrase..","premiumpress"),
		"8" 			=> __("I'm currently located at","premiumpress"),
		"9" 			=> __("Looking for","premiumpress"),
		"10" 			=> __("Within distance","premiumpress"),
		"11" 			=> __("In","premiumpress"),
		"12"			=> __("Website Listings","premiumpress"),
		"13"			=> __("Popular Searches","premiumpress"),
		"14"			=> __("Recently Added","premiumpress"),
		"15"			=> __("Most Popular","premiumpress"),
		"16"			=> __("Best Sellers","premiumpress"),
		"17"			=> __("Most Viewed","premiumpress"),
		"18"			=> __("Featured Listings","premiumpress"),
		"19"			=> __("Latest News","premiumpress"),
		"20"			=> __("View All Categories","premiumpress"),
	),

	"single" => array(
		"0" 			=> __("Related Listing","premiumpress"),
		"1" 			=> __("Contact Author","premiumpress"),
		"2" 			=> __("Your Name","premiumpress"),
		"3" 			=> __("Your Email","premiumpress"),
		"4" 			=> __("Your Phone","premiumpress"),
		"5" 			=> __("What is the sum of:","premiumpress"),
		"6" 			=> __("Your Message","premiumpress"),
		"7" 			=> __("Send Message","premiumpress"),
		"8" 			=> __("Message Sent","premiumpress"),
		"9" 			=> __("Security Code Incorrect","premiumpress"),
		"10" 			=> __("Edit This Listing","premiumpress"),
		"11" 			=> __("Make Payment","premiumpress"),
		"12" 			=> __("This listing is awaiting payment and is NOT live.","premiumpress"),
		"13" 			=> __("Payment Options","premiumpress"),
		"14" 			=> __("Close","premiumpress"),
		"15" 			=> __("Listing Author","premiumpress"),
		"16" 			=> __("Listing Details","premiumpress"),
		"17" 			=> __("Date Created","premiumpress"),
 		"18" 			=> __("Last Modified","premiumpress"),
	 	"19" 			=> __("Views","premiumpress"),
		"20" 			=> __("Expires","premiumpress"),
		"21" 			=> __("Note: This information is only visible to the listing author and not visible to the public.","premiumpress"),
		"22" 			=> __("Does this listing belong to your company?","premiumpress"),
		"23" 			=> __("Click here to claim this listing.","premiumpress"),
		"24" 			=> __("Print this page","premiumpress"),
		"25" 			=> __("Visit Link Here","premiumpress"),
		"26" 			=> __("Name","premiumpress"),
		"27" 			=> __("Email","premiumpress"),
		"28" 			=> __("Phone","premiumpress"),
		"29" 			=> __("Message","premiumpress"),
		"30" 			=> __("Post Link","premiumpress"),
		"31" 			=> __("Renew Listing","premiumpress"),
		"32"			=> __("%a for an additional %b days.","premiumpress"),
		"33" 			=> __("hits","premiumpress"),
		"34" 			=> __("Description","premiumpress"),
		"35" 			=> __("Details","premiumpress"),
		"36" 			=> __("Contact","premiumpress"),
		"37" 			=> __("Comments","premiumpress"),
		"38" 			=> __("Price Comparison","premiumpress"),
		"39" 			=> __("Attachments","premiumpress"),
		"40" 			=> __("Article ID","premiumpress"),
		"41" 			=> __("Facebook Share","premiumpress"),
		"42" 			=> __("Tweet Article","premiumpress"),
		"43" 			=> __("Export PDF","premiumpress"),
		"44" 			=> __("Bookmark","premiumpress"),
		"45" 			=> __("Email Article","premiumpress"),
		"46" 			=> __("Leave Comment","premiumpress"),
		"47" 			=> __("Be the first to review this listing","premiumpress"),
	 	"48" 			=> __("This listing expires in ","premiumpress"),
		"49"			=> __("Complete the fields below to contact this listing author.","premiumpress"),
		"50"			=> __("Your Rating","premiumpress"),
		"51"			=> __("Beds","premiumpress"),
		"52"			=> __("Baths","premiumpress"),
		"53"			=> __("Sq Ft","premiumpress"),
		"54"			=> __("Likes","premiumpress"),
		"55"			=> __("My Photos","premiumpress"),
		"56"			=> __("About Me","premiumpress"),
		"57"			=> __("Unknown","premiumpress"),
	),

	"gallerypage" => array(
		"0" 			=> __("Search Results","premiumpress"),
		"1" 			=> __("We have found <b class='num'>%a</b> items matching your search query.","premiumpress"),
		"6" 			=> __("Page %CURRENT_PAGE% of %TOTAL_PAGES%","premiumpress"),
		"7" 			=> __("<< First","premiumpress"),
		"8" 			=> __("Last >>","premiumpress"),
		"9" 			=> __("Sort By","premiumpress"),
		"10"			=> __("Title","premiumpress"),
		"11"			=> __("Title","premiumpress"),
		"12"			=> __("Date","premiumpress"),
		"13"			=> __("Date","premiumpress"),
		"14"			=> __("Price","premiumpress"),
		"15"			=> __("Price","premiumpress"),
		"16"			=> __("Sorry, no listing matched your criteria.","premiumpress"),
		"17"			=> __("Featured Category Listings","premiumpress"),
		"18"			=> __("Get Directions","premiumpress"),
		"19"			=> __("Listings Nearby","premiumpress"),
		"20"			=> __("Useful Links","premiumpress"),
		"21"			=> __("Nearest","premiumpress"),
		"22"			=> __("Furthest","premiumpress"),
		"23"			=> __("Order","premiumpress"),
		"24"			=> __("Nothing Found","premiumpress"),
		"25"			=> __("This is somewhat embarrassing, isn&rsquo;t it?","premiumpress"),
		"26"			=> __("It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching can help.","premiumpress"),
		"27"			=> __("0 Results Found","premiumpress"),
		"28"			=> __("There were no results found for your search query.","premiumpress"),
		"29"			=> __("We did not find any results for your search query. Please try again with a different search query.","premiumpress"),

		"30"			=> __("Expiry Date","premiumpress"),
		"31"			=> __("Expiry Date","premiumpress"),

		"32"			=> __("Popularity","premiumpress"),
		"33"			=> __("Rating","premiumpress"),
		"34"			=> __("Featured","premiumpress"),
	),

	"add" => array(
		"1" 			=> __("Listing Packages","premiumpress"),
		"2" 			=> __("More Info","premiumpress"),
		"3" 			=> __("Subscribe","premiumpress"),
		"4" 			=> __("Close","premiumpress"),
		"5" 			=> __("Listing Details","premiumpress"),
		"6" 			=> __("Package","premiumpress"),
		"7" 			=> __("How does this work?","premiumpress"),
		"8" 			=> __("Once you have completed the options below your new listing will be created but <b>will not go live</b> until payment has been received. This gives you time to check, modify and preview the listing before payment.","premiumpress"),
		"9" 			=> __("Contact Email","premiumpress"),
		"10" 			=> __("Title","premiumpress"),
		"11" 			=> __("Tag line","premiumpress"),
		"12" 			=> __("Description","premiumpress"),
		"13" 			=> __("Category","premiumpress"),
		"14" 			=> __("Display File","premiumpress"),
		"15" 			=> __("<strong>Notice</strong>  Once your listing has been saved you will be able to upload additional images.","premiumpress"),
		"16" 			=> __("Save listing","premiumpress"),
		"17" 			=> __("Media Manager","premiumpress"),
		"18" 			=> __("Add files...","premiumpress"),
		"19" 			=> __("Upload All","premiumpress"),
		"20" 			=> __("Start","premiumpress"),
		"21"			=> __("Cancel","premiumpress"),
		"22"			=> __("Error","premiumpress"),
		"23"			=> __("Please provide more details, your listing is too short.","premiumpress"),
		"24"			=> __("Membership Packages","premiumpress"),
		"25"			=> __("Our membership packages let you submit multiple listings.","premiumpress"),
		"26"			=> __("Per Listing Packages","premiumpress"),
		"27"			=> __("Our per listing packages let you pay for each listing separately.","premiumpress"),
		"28"			=> __("All listings are removed once the listing or membership has expired unless renewed beforehand.","premiumpress"),
		"29"			=> __("Saving Your Changes","premiumpress"),
		"30"			=> __("This may take a few minutes so please wait...","premiumpress"),
		"31"			=> __("Listing Enhancements","premiumpress"),
		"32"			=> __("Enhance your listing with any of the additional features below;","premiumpress"),
		"33"			=> __("Total Payment","premiumpress"),
		"34"			=> __("for a %a day listing.","premiumpress"),
		"34b"			=> __("for an <b>extra</b> %a day listing.","premiumpress"),
		"34a"			=> __("for a %a day membership.","premiumpress"),
		"35"			=> __("Account Creation","premiumpress"),
		"36"			=> __("If you are already a member please login otherwise we will auto create a new account for you with the email address you provide above.","premiumpress"),
		"37"			=> __("Location","premiumpress"),
		"38"			=> __("Click on the map below to zoom in and place a market on the location of your item or company.","premiumpress"),
		"39"			=> __("Please select a valid location on the map.","premiumpress"),
		"40"			=> __("Front Page Exposure","premiumpress"),
		"41"			=> __("Featured Listing","premiumpress"),
		"42"			=> __("HTML Listing Content","premiumpress"),
		"43"			=> __("Visitor Counter","premiumpress"),
		"44"			=> __("Top of Category","premiumpress"),
		"45"			=> __("Google Map","premiumpress"),
		"40d"			=> __("Purchase this listing enhancement and see your listing featured on our home page!
			<p> Our home page listings generate 60% more exposure and is a great way to get your listing seen by more visitors.</p>","premiumpress"),
		"41d"			=> __("Purchase this listing enhancement and see your listing highlighted in search results! <p> What better way to get your listing seen by visitors searching the website than with a highlighted listing standing out above the rest!</p>","premiumpress"),
		"42d"			=> __("Purchase this listing enhancement and bring your listing to life with HTML content! <p> Customize your listing description with your own formatting, content and images with this feature.</p>","premiumpress"),
		"43d"			=> __("Purchase this listing enhancement and we'll monitor your listing visits. <p>Find out which of your listings is performing better with our visitor counter which will record all clicks on your listings and display then to you (visible to you only) at the bottom of your listings.</p>","premiumpress"),
		"44d"			=> __("Purchase this listing enhancement and we'll feature your listing at the top of your chosen category pages.<p> This great feature will bring more exposure to your listing. Whenever a user searches a chosen category your listing will appear before all others at the top.</p>","premiumpress"),
		"45d"			=> __("Purchase this listing enhancement and we'll display a map on your listing page.","premiumpress"),
		"46"			=> __("You current map location is;","premiumpress"),
		"47"			=> __("Country","premiumpress"),
		"48"			=> __("State/Province","premiumpress"),
		"49"			=> __("City","premiumpress"),
		"50"			=> __("<b>File Attachments</b> <br />
		Once saved, new options will be available for you to upload file attachments.","premiumpress"),
		"51"			=> __("Please enter your location.","premiumpress"),
		"52"			=> __("We have detected you already have an account with us. Please login to your existing account to edit/modify your listings.","premiumpress"),
		"53"			=> __("Select Payment Method","premiumpress"),
		"54"			=> __("Enter your physical location here.","premiumpress"),
		"55"			=> __("included","premiumpress"),
		"56"			=> __("Free","premiumpress"),
		"57"			=> __("Account Upgraded","premiumpress"),
		"58"			=> __("Your account has been upgraded to this new membership.","premiumpress"),
		"59"			=> __("Never Expires","premiumpress"),
		"60"			=> __("Upgrade Options","premiumpress"),
		"61"			=> __("Acceptable File Formats: jpg/.gif/.png/.pdf/.flv/.mp4/.mp3","premiumpress"),
		"62"			=> __("Upto %a Listings","premiumpress"),
		"63"			=> __("Listing Description","premiumpress"),
		"64"			=> __("Listing Category","premiumpress"),
		"65"			=> __("Listing Attachments","premiumpress"),
		"66"			=> __("Listing Details","premiumpress"),
		"67"			=> __("Listing Location","premiumpress"),
		"68"			=> __("Display Image","premiumpress"),
		"69"			=> __("Listing Information","premiumpress"),
		"70"			=> __("None Set","premiumpress"),
		"71"			=> __("Keywords","premiumpress"),
		"72"			=> __("Enter a value below to create a new option.","premiumpress"),
		"73"			=> __("Separate each keyword with a comma.","premiumpress"),
		"74"			=> __("Display Order","premiumpress"),
		"75"			=> __("Parent Category <small class='right'>Hold CTRL to select multiple categories</small>","premiumpress"),
		"76"			=> __("Sub Category","premiumpress"),
		"77"			=> __("Sub Sub Category","premiumpress"),
		"78"			=> __("Sub Sub Sub Category","premiumpress"),
		"79"			=> __("<b>Parent Category Disabled.</b> Listings will only appear in sub categories.","premiumpress"),
		"80"			=> __("You have selected too many categories. Only the first %a will be saved.","premiumpress"),
		"81"			=> __("maximum categories.","premiumpress"),
		"82"			=> __("selected.","premiumpress"),
		"83"			=> __("You can select up to %a media files.","premiumpress"),
		"84"			=> __("add images","premiumpress"),
		"85"			=> __("add videos","premiumpress"),
		"86"			=> __("add music","premiumpress"),
		"87"			=> __("add docs","premiumpress"),
		"88"			=> __("Edit Media","premiumpress"),
		"89"			=> __("all files","premiumpress"),
		"90"			=> __("images only","premiumpress"),
		"91"			=> __("videos only","premiumpress"),
		"92"			=> __("music only","premiumpress"),
		"93"			=> __("docs only","premiumpress"),
		"94"			=> __("Listing:","premiumpress"),
		"95"			=> __("Minimum of %a characters.","premiumpress"),
		"96"			=> __("characters remaining.","premiumpress"),
		"97"			=> __("Edit Listing","premiumpress"),
		"98"			=> __("You can edit your details listing below.","premiumpress"),
		"99"			=> __("ASDFASDF","premiumpress"),		
	),

	"checkout" => array(
		"1" 					=> __("Item Name","premiumpress"),
		"2" 					=> __("Price","premiumpress"),
		"3" 					=> __("QTY","premiumpress"),
		"4" 					=> __("Total","premiumpress"),
		"5" 					=> __("remove","premiumpress"),
		"6" 					=> __("Sub Total","premiumpress"),
		"7" 					=> __("Shipping","premiumpress"),
		"8" 					=> __("Tax","premiumpress"),
		"9" 					=> __("Discount","premiumpress"),
		"10" 					=> __("Empty Cart","premiumpress"),
		"11" 					=> __("Basket Updated","premiumpress"),
		"12" 					=> __("<b>Congratulations!</b> Your basket has been updated, what would you like to do now?","premiumpress"),
		"13" 					=> __("Continue Shopping","premiumpress"),
		"14" 					=> __("Checkout Now","premiumpress"),
		"15" 					=> __("item(s)","premiumpress"),
		"16" 					=> __("Add to Cart","premiumpress"),
		"17" 					=> __("items","premiumpress"),
		"18" 					=> __("Download Now","premiumpress"),
		"19" 					=> __("Please select a value for %a.","premiumpress"),
		"20" 					=> __("Minimum order:","premiumpress"),
		"21" 					=> __("items","premiumpress"),
		"22" 					=> __("downloads","premiumpress"),
		"23" 					=> __("Step 1: Checkout Options","premiumpress"),
		"24" 					=> __("Welcome back","premiumpress"),
		"25" 					=> __("New Customer","premiumpress"),
		"26" 					=> __("Creating a new account takes only a few seconds, its completely free and will help you manage your order, delivery and account details.","premiumpress"),
		"27" 					=> __("click here to register","premiumpress"),
		"28" 					=> __("Registered Customers","premiumpress"),
		"29" 					=> __("If you have an account with us, please log in.","premiumpress"),
		"30" 					=> __("click here to login","premiumpress"),
		"31" 					=> __("Step 2: Delivery Details","premiumpress"),
		"32" 					=> __("Continue","premiumpress"),
		"33" 					=> __("Step 3: Payment Method","premiumpress"),
		"34" 					=> __("Your Delivery Details","premiumpress"),
		"35" 					=> __("First Name","premiumpress"),
		"36" 					=> __("Last Name","premiumpress"),
		"37" 					=> __("Email Address","premiumpress"),
		"38" 					=> __("Telephone","premiumpress"),
		"39" 					=> __("Country","premiumpress"),
		"40" 					=> __("Preferred Delivery Method","premiumpress"),
		"41" 					=> __("Address","premiumpress"),
		"42" 					=> __("Address 2","premiumpress"),
		"43" 					=> __("City","premiumpress"),
		"44" 					=> __("ZIP/Postal Code","premiumpress"),
		"45" 					=> __("State/Region","premiumpress"),
		"46" 					=> __("Your basket is empty","premiumpress"),
		"47" 					=> __("Have any comments or feedback regarding this order?","premiumpress"),
		"48" 					=> __("No Stock","premiumpress"),
		"49" 					=> __("Product","premiumpress"),
		"50" 					=> __("Best Price","premiumpress"),
		"51" 					=> __("Visit Store","premiumpress"),
		"52" 					=> __("Guest Checkout","premiumpress"),
		"53" 					=> __("Members Only - Please login to use this feature.","premiumpress"),
		"54" 					=> __("Weight","premiumpress"),
		"55" 					=> __("Remove Item","premiumpress"),
		"56"					=> __("Availability","premiumpress"),
		"57"					=> __("In Stock","premiumpress"),
		"58"					=> __("Added","premiumpress"),
		"59"					=> __("shop now","premiumpress"),

		"60"					=> __("User Credit Payment","premiumpress"),
		"61"					=> __("your current balance is","premiumpress"),
		"62"					=> __("No Comments Added","premiumpress"),


		"71" 			=> __("Invalid Coupon Code","premiumpress"),
		"72" 			=> __("Coupon Discount Applied.","premiumpress"),
		"73" 			=> __("Apply discount code","premiumpress"),
		"74" 			=> __("Discount code:","premiumpress"),
		"75" 			=> __("Enter your coupon here","premiumpress"),
		"76" 			=> __("You can only use one discount code at a time","premiumpress"),
		"77" 			=> __("Apply Coupon","premiumpress"),
	),

	"account" => array(

		"1" 			=> __("Welcome to your account area.","premiumpress"),
		"2" 			=> __("My Account","premiumpress"),
		"3" 			=> __("Here you can view, modify and update your account details.","premiumpress"),
		"4" 			=> __("Create Listing","premiumpress"),
		"5" 			=> __("Here you can create a new website listing.","premiumpress"),
		"6" 			=> __("My Listings","premiumpress"),
		"7" 			=> __("Here you can view your existing website listing.","premiumpress"),
		"8" 			=> __("Logout","premiumpress"),
		"9" 			=> __("Email","premiumpress"),
		"10" 			=> __("Password","premiumpress"),
		"11" 			=> __("Re-Type Password","premiumpress"),
		"12" 			=> __("No money has been taken from your account, the transaction was not completed successfully.","premiumpress"),
	 	"13" 			=> __("About Me/ Extra Details","premiumpress"),
	 	"14" 			=> __("Website","premiumpress"),
		"15" 			=> __("View All Listings","premiumpress"),
		"16" 			=> __("Message Deleted","premiumpress"),
		"17" 			=> __("Message Sent Successfully","premiumpress"),
		"18" 			=> __("Username not found","premiumpress"),
		"19" 			=> __("Profile Data Updated","premiumpress"),
		"20" 			=> __("New Password Invalid","premiumpress"),
		"21" 			=> __("Profile Data Updated","premiumpress"),
		"22" 			=> __("Listing Successfully Removed","premiumpress"),
		"23" 			=> __("
		<h4>Thank You</h4> This listing has now been assigned to your account.","premiumpress"),
		"24" 			=> __("<h4>Too Many Claims!</h4> Our system shows you have already claimed a listing before. <br/>Please contact our management team if you wish to claim any further listings.","premiumpress"),
		"25" 			=> __("<h4>Submission Limit Reached</h4> You have reached your membership submission limit. Please delete an existing listing or upgrade your membership.","premiumpress"),
		"26" 			=> __("My Messages","premiumpress"),
		"27" 			=> __("Here you can view any messages sent by our website members.","premiumpress"),
		"28" 			=> __("%a New Message","premiumpress"),
		"29" 			=> __("Send Message","premiumpress"),
		"30" 			=> __("Fill out the fields below to send a private message to one of our members.","premiumpress"),
		"31" 			=> __("Member Username","premiumpress"),
		"32" 			=> __("Subject","premiumpress"),
		"33" 			=> __("Message","premiumpress"),
		"34" 			=> __("Send Message","premiumpress"),
		"35" 			=> __("Status","premiumpress"),
		"36" 			=> __("Subject","premiumpress"),
		"37" 			=> __("Date","premiumpress"),
		"38" 			=> __("Compose Message","premiumpress"),
		"39" 			=> __("Your inbox is empty.","premiumpress"),
		"40" 			=> __("a website visitor","premiumpress"),
		"41" 			=> __("Phone","premiumpress"),
		"42"			=> __("Email subscriptions have been updated","premiumpress"),
		"43"			=> __("Membership Enabled","premiumpress"),
		"44"			=> __("My Subscriptions","premiumpress"),
		"45"			=> __("Here you can subscribe to our website categories and receive an email when a new listing is added.","premiumpress"),
		"46"			=> __("My Favorites","premiumpress"),
		"47"			=> __("Here you can view and manage your favorites list.","premiumpress"),
		"48"			=> __("Hide Form","premiumpress"),
		"49"			=> __("Select categories which you would like to subscribe to below. Whenever a new listing is created within one of your selected categories we will send you an email.","premiumpress"),
		"50"			=> __("Actions","premiumpress"),
		"51"			=> __("Title","premiumpress"),
		"52"			=> __("Remove Favorites","premiumpress"),
		"53"			=> __("<h4>Your List is Empty</h4> Looks like you haven't added anything yet.","premiumpress"),
		"54"			=> __("Withdrawal","premiumpress"),
		"55"			=> __("Here you can withdraw money from your account.","premiumpress"),
		"56"			=> __("Please complete the fields below, we will contact you within 48 hours regarding your request.","premiumpress"),
		"57"			=> __("Your current balance is:","premiumpress"),
		"58"			=> __("<b>Note.</b> All withdrawals are subject to a %%a service fee.","premiumpress"),
		"59"			=> __("How much would you like to withdraw?","premiumpress"),
		"60"			=> __("Payment Preferences","premiumpress"),
		"61"			=> __("Send Request","premiumpress"),
		"62"			=> __("[IMPORTANT] Payment Withdrawal Request","premiumpress"),
		"63"			=> __("Thank You. Your request has been sent.","premiumpress"),
		"64"			=> __("<h4>Pending User Changes</h4><p>Please adjust your listing according to the admin comments below;</p>","premiumpress"),
		"65"			=> __("<h4>Pending Admin Approval</h4> <p>Your listing will go live once it has been approved by a website admin.<br /><b>Thank you for your patience.</b>","premiumpress"),
		"66"			=> __("<h4>Current Item Status:</h4>","premiumpress"),
		"67"			=> __("Renew Now","premiumpress"),
		"68"			=> __("Photo","premiumpress"),
		"69"			=> __("Remove From List","premiumpress"),
		"70"			=> __("My Friends/Blocked List","premiumpress"),
		"71"			=> __("Here you can view users you have added as friends and/or blocked.","premiumpress"),
		"72"			=> __("My Friends","premiumpress"),
		"73"			=> __("My Blocked User List","premiumpress"),
		"74"			=> __("Listing Updated","premiumpress"),
		"75"			=> __("Read","premiumpress"),
		"76"			=> __("New","premiumpress"),
		"77"			=> __("Negative Amount Balance","premiumpress"),
		"78"			=> __("Amount due %a. Please make payment as soon as possible.","premiumpress"),
		"79"			=> __("Display Photo","premiumpress"),
		"80"			=> __("Invalid Membership Access - Please upgrade your membership to access this feature.","premiumpress"),
		"81"			=> __("Feedback","premiumpress"),
		"82"			=> __("Here you can view feedback left and received.","premiumpress"),
		"83"			=> __("Select All","premiumpress"),
		"84"			=> __("Delete Selected","premiumpress"),
		"85"			=> __("Profile Background","premiumpress"),
		"86"			=> __("Social Media","premiumpress"),
		"87"			=> __("login's.","premiumpress"),
		"88"			=> __("Joined %a ago.","premiumpress"),

		"89"			=> __("Premium Advertising","premiumpress"),
		"90"			=> __("Advertising","premiumpress"),
		"91"			=> __("My Banners","premiumpress"),
		"92"			=> __("My Orders","premiumpress"),
		"93"			=> __("no active orders found","premiumpress"),
		"94"			=> __("My Orders","premiumpress"),
		"95"			=> __("Size","premiumpress"),
		"96"			=> __("Impressions","premiumpress"),
		"97"			=> __("Clicks","premiumpress"),
		"98"			=> __("Select Banner","premiumpress"),
		"99"			=> __("Please update a banner with the dimensions","premiumpress"),
		"100"			=> __("Enter Banner Link","premiumpress"),
		"101"			=> __("Upload Banner","premiumpress"),
		"102"			=> __("My Banners","premiumpress"),
		"103"			=> __("Available Advertising Opportunities","premiumpress"),
		"104"			=> __("Accepted formats are: jpg/jpeg/gif","premiumpress"),
		"105"			=> __("Banner Set Successfully","premiumpress"),
		"106"			=> __("Banner Deleted Successfully","premiumpress"),
		"107"			=> __("File Type Invalid","premiumpress"),
		"108"			=> __("Banners Saved Successfully","premiumpress"),
		"109"			=> __("Recently Viewed","premiumpress"),
		"110"			=> __("No recent history","premiumpress"),

		"111"			=> __("My Favorite Listings","premiumpress"),
		"112"			=> __("No favorites found","premiumpress"),

		"113"			=> __("new messages","premiumpress"),
		"114"			=> __("listings created","premiumpress"),
		"115"			=> __("orders made","premiumpress"),
		"116"			=> __("Account Options","premiumpress"),

	),

	"callback" => array(
		"1" 			=> __("Payment Complete","premiumpress"),
		"2" 			=> __("Thank you for your order.","premiumpress"),
		"3" 			=> __("Your order has now been completed, you will be contacted by our team shortly.","premiumpress"),
		"7" 			=> __("Payment Failed","premiumpress"),
		"8" 			=> __("Sorry but there was an error during checkout.","premiumpress"),
		"9" 			=> __("No money has been taken from your account.","premiumpress"),
		"10"			=> __("Return to website listing.","premiumpress"),
	),

	"comment" => array(

		"1" 			=> __("This post is password protected. Enter the password to view comments.","premiumpress"),
		"2" 			=> __("Comments are closed.","premiumpress"),
		"3" 			=> __("You must be logged in to post a comment.","premiumpress"),
		"4" 			=> __("Name","premiumpress"),
		"5" 			=> __("Mail (will not be published)","premiumpress"),
		"6" 			=> __("Website","premiumpress"),
		"7" 			=> __("Submit Comment","premiumpress"),
		"8" 			=> __("Leave a Comment","premiumpress"),
		"9" 			=> __("No Comments","premiumpress"),
		"10" 			=> __("1 Comment","premiumpress"),
		"11" 			=> __("Comments","premiumpress"),
		"12"			=> __("+ Add Comment","premiumpress"),
		"13"			=> __("Comment Added Successfully.","premiumpress"),
	),

	"login" => array(
		"1" 		=> __("Member Login","premiumpress"),
		"2" 		=> __("Not yet a member?","premiumpress"),
		"3" 		=> __("Click here to register a new account.","premiumpress"),
		"4" 		=> __("Submit","premiumpress"),
		"5" 		=> __("Forgotten Password?","premiumpress"),
		"6" 		=> __("Register New Account","premiumpress"),
		"7" 		=> __("A password will be emailed to you.","premiumpress"),
		"8" 		=> __("Enter your username or email below;","premiumpress"),
		"9" 		=> __("Send me a new password","premiumpress"),
		"10" 		=> __("Username","premiumpress"),
		"11" 		=> __("<h1>Account Pending</h1><p>Your account is still under review, once approved you will be able to login.</p>","premiumpress"),
		"12" 		=> __("<h1>Account Suspended</h1><p>We are sorry but your account has been suspended.</p>","premiumpress"),
		"13" 		=> __("<h1>You're Fired!!</h1><p>We are sorry but your account has been terminated and you are now fired.</p>
		","premiumpress"),
		"14" 		=> __("<strong>ERROR</strong>: You didn't correctly enter the captcha, please try again.","premiumpress"),
		"15" 		=> __("Enter your account username or email below and we will send you a new password.","premiumpress"),
		"16" 		=> __("Complete the fields below to register a new account. Your login username and password will be sent to the email address you enter below.","premiumpress"),
		"17" 		=> __("Please Try Again","premiumpress"),
		"18" 		=> __("Create Account","premiumpress"),
		"19" 		=> __("Select","premiumpress"),
		"20" 		=> __("Selected","premiumpress"),
		"_zz1" 					=> __("Type the code above:","premiumpress"),
		"_zz2" 					=> __("A password will be e-mailed to you.","premiumpress"),
		"_zz3" 					=> __("Username or Email:","premiumpress"),
		"_zz4" 					=> __("Get New Password","premiumpress"),
		"_zz5" 					=> __("Please enter your username or e-mail address. You will receive a new password via e-mail.","premiumpress"),
		"_zz6" 					=> __("Sorry, that key does not appear to be valid.","premiumpress"),
		"_zz7" 					=> __("You are now logged out.","premiumpress"),
		"_zz8" 					=> __("User registration is currently not allowed.","premiumpress"),
		"_zz9" 					=> __("Check your e-mail for the confirmation link.","premiumpress"),
		"_zz10" 				=> __("Check your e-mail for your new password.","premiumpress"),
		"_zz11" 				=> __("Registration complete.","premiumpress"),
		"reg1" 		=> __("Account Login Details","premiumpress"),
		"21" 		=> __("The validation answer is incorrect","premiumpress"),
		"22" 		=> __("We are protecting ourselves from spam,<a href='%a'> please click here to register. </a>","premiumpress"),

		"23" 		=> __("Already a Member?","premiumpress"),
		"24" 		=> __("Get started now. Login to your account.","premiumpress"),
		"25" 		=> __("New to our website?","premiumpress"),
		"26" 		=> __("Get started now. It's fast and easy.","premiumpress"),
		"27" 		=> __("New Password","premiumpress"),

		"28" 		=> __("Confirm new password","premiumpress"),
		"29" 		=> __("Reset Password","premiumpress"),

		"30" 		=> __("Membership Options","premiumpress"),
		"31" 		=> __("Please select a membership package from the list below.","premiumpress"),
		"32" 		=> __("Please select a membership package.","premiumpress"),
 		"33" 		=> __("The login credentials you entered were incorrect.","premiumpress"),
	),

	"listvalues" => array(
		"title" 	=> __("Listing Status","premiumpress"),
		"0" 		=> __("Active / Available / Open","premiumpress"),
		"1" 		=> __("Un-Available","premiumpress"),
		"2" 		=> __("Leased","premiumpress"),
		"3" 		=> __("Rented","premiumpress"),
		"4" 		=> __("Pending Sale","premiumpress"),
		"5" 		=> __("Sold","premiumpress"),
		"6" 		=> __("Finished","premiumpress"),
		"7" 		=> __("Closed","premiumpress"),
		"8" 		=> __("Abandoned","premiumpress"),
	),

	"graphs" => array(
		"1" 			=> __("Visitor History","premiumpress"),
		"2" 			=> __("Date","premiumpress"),
		"3" 			=> __("Unique Visitors","premiumpress"),
		"4" 			=> __("Visitors","premiumpress"),
	),


	// UPDATED JUNE 2014
	"feedback" => array(
		"0"				=> __("User Feedback","premiumpress"),
		"1" 			=> __("Leave Feedback","premiumpress"),
		"2" 			=> __("Feedback","premiumpress"),
		"3" 			=> __("read more","premiumpress"),
		"4" 			=> __("read less","premiumpress"),
		"5" 			=> __("Trust Factor","premiumpress"),
		"6" 			=> __("Feedback Deleted","premiumpress"),
		"7" 			=> __("Feedback Added Successfully","premiumpress"),
		"8" 			=> __("Feedback Found","premiumpress"),
		"9" 			=> __("Delete Feedback","premiumpress"),
		"10" 			=> __("Older","premiumpress"),
		"11" 			=> __("Newer","premiumpress"),
		"12" 			=> __("No Feedback Found","premiumpress"),
		"13" 			=> __("To add feedback for a listing view the listing and click on the leave feedback button.","premiumpress"),
		"14" 			=> __("Complete the fields below to leave feedback for this listing and user.","premiumpress"),
		"15"			=> __("Feedback has already been left for this item","premiumpress"),
		"16"			=> __("You can only leave 1 feedback per listing.","premiumpress"),
		"17"			=> __("Feedback Title","premiumpress"),
		"18"			=> __("Feedback Description","premiumpress"),
		"19"			=> __("My Rating","premiumpress"),
		"20"			=> __("Submit Feedback","premiumpress"),
		"21"			=> __("No Feedback Received","premiumpress"),
		"22"			=> __("Item","premiumpress"),
		"23"			=> __("Purchased","premiumpress"),
		"24"			=> __("My Feedback","premiumpress"),
		"37" 			=> __("User Feedback","premiumpress"),
		"46" 			=> __("<i class='fa fa-star'></i> Leave Feedback","premiumpress"),
		"publish" 			=> __("Live Feedback","premiumpress"),
		"pending" 			=> __("Awaiting Approval","premiumpress"),
		"draft" 			=> __("Removed by User","premiumpress"),
		"47"				=> __("User Rating","premiumpress"),
	),


	"review" => array(
		"1" 			=> __("Price","premiumpress"),
		"2" 			=> __("Overall","premiumpress"),
	),

	"mobile" => array(
		"1" 			=> __("Latest Listings","premiumpress"),
	 	"2" 			=> __("My Account","premiumpress"),
		"3"				=> __("Contact Us","premiumpress"),
		"4" 			=> __("Website Navigation","premiumpress"),
	),

	"class" => array(
		"1" 			=> __("Advert","premiumpress"),
		"2" 			=> __("additional contact options","premiumpress"),
 		"3"				=> __("Private Message","premiumpress"),
	),

),
);
?>
